### PR TITLE
Chapter 2 cleanup

### PR DESCRIPTION
**Pull request by wal**
Hey Adam,

Sorry this is a big PR 😢 

A few things .. 

1. I created a shared ```save_and_show_plot``` function to do both the saving and displaying of a chart using your dev.new approach. I previously wasn't focusing on the outputted png chart files and it turns out some of the charts in the png files I generated were messed up which I didnt realise. I went back through the chapter 2 charts and used this function. I think they are better now ?

2. I made some tweaks to the base theme_swd function as the font sizes in the generated files were huge. Also a few small tweaks to some of the earlier chart files to use the theme via theme_set to be consistent, etc

3. I refactored 0227 to use the patchwork library to assemble the multiple charts rather than saving and rereading images, I think its a little bit tidier. Let me know what you think.

thanks, this has been a great learning / tweaking exercise so far

### CODE REVIEW

**Comment by adamribaudo** [comment]
Thanks! Cleanup looks good.

I don't love the `save_and_show_plot` solution. If you think of the workflow, you need to open and close a new window every time you want to preview. That said, the alternative isn't much better (commenting out dev.new() after the window opens the first time). 

I'm constantly frustrated by RStudio's inability to preview a plot exactly as it will be saved. I've poked at this issue a few times and come up short:

https://community.rstudio.com/t/how-to-save-plots-in-code-as-they-appear-in-the-rstudio-plots-pane/70008
https://community.rstudio.com/t/how-can-i-recreate-the-image-resolution-quality-shown-in-r4ds/65903

I even found an instance where there were differences between the dev.new() preview specifying the same height/width as ggsave(). 

Let me know if you come across any elegant solutions.

**Comment by wal** [comment]
hey, yeah interesting thoughts and discussion on the rstudio community page. I hadn't thought about this before but thinking through your descriptions it seems mad you cant preview exactly what you will write to disk ..  😕 

totally happy to tear out the ```save_and_show_plot``` thing if you think its too contrived/awkward, I guess we want this to be really easy for someone new to the SWD book and maybe R to run the code easily and not get tripped up with strange things or errors so whatever you think is best for that objective.

thanks

**Comment by adamribaudo** [comment]
It's funny, before you mentioned it I hadn't thought deeply about how
others might use this code. It started as a personal challenge but would be
much more valuable as a teaching tool. I should really do a better job of
commenting, huh.

With all that in mind, I think the dev.new() workflow is something we
should keep in our back-pocket as a way to identify the correct
width/height to use in ggsave but leave it out of the code. A newbie
reading the code would see the plot in RStudio's preview pane and wouldn't
second guess how we figured out the width/height in the ggsave call. We can
spare them that ugly detail.

How's that sound?

**Comment by wal** [comment]
yeah that makes sense to me .. saw you commented it out there which is cool 👍

**Pull request merged**
